name: meali
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  kakao_flutter_sdk_user: ^1.9.6
  kakao_flutter_sdk_talk: ^1.9.6
  kakao_flutter_sdk_share: ^1.9.6
  flutter_dotenv: ^5.0.2
  http: ^1.2.2
  go_router: ^14.6.2
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # images
    - assets/images/users_icon.png
    - assets/images/hamburger_icon.png
    - assets/images/test_user_image.jpeg
    - assets/images/test_user_image2.jpeg
    - assets/images/arrow_drop_down_icon.png
    - assets/images/add_user_icon.png
    - assets/images/temp_icon.png
    - assets/images/temp_icon2x.png
    - assets/images/kakao_login_button.png
    - assets/images/write_icon.png
    - assets/images/selected_icon.png
    # environment vars.
    - .env

  fonts:
    - family: PretendardVariable
      fonts:
        - asset: assets/fonts/PretendardVariable.ttf
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.otf
          weight: 900
    - family: PartialSans
      fonts:
        - asset: assets/fonts/PartialSansKR-Regular.otf

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
