name: meali
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  kakao_flutter_sdk_user: ^1.9.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/users_icon.png
    - assets/images/hamburger_icon.png
    - assets/images/test_user_image.jpeg
    - assets/images/arrow_drop_down_icon.png
    - assets/images/add_user_icon.png

fonts:
  - family: PretendardVariable
    font:
      - asset: assets/fonts/PretendardVariable.ttf
  - family: Pretendard
    font:
      - asset: assets/fonts/Pretendard-Thin.ttf
        weight: 100
      - asset: assets/fonts/Pretendard-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/Pretendard-Light.ttf
        weight: 300
      - asset: assets/fonts/Pretendard-Regular.ttf
        weight: 400
      - asset: assets/fonts/Pretendard-Medium.ttf
        weight: 500
      - asset: assets/fonts/Pretendard-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Pretendard-Bold.ttf
        weight: 700
      - asset: assets/fonts/Pretendard-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Pretendard-Black.ttf
        weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
